### ISSUE TITLE
Automated email for password reset

### ISSUE THREAD

**Issue by bentsherman** [wsbf/wsbf.net#17]
I've tried to implement automated email for the password reset form but I haven't been able to send email, not even to my spam folder. There could be a problem with my code, or with the Apache-PHP stack, or maybe I can't send email from `computer@wsbf.net` because it's just a forwarding-rule on Namecheap. In any case, if anyone could ever implement this it would be very helpful for people who forget their passwords (and the computer engineer who has to fetch the reset URL for them).

**Comment by jagarwa1** [comment]
Implemented new mailboxes and use PHPMailer to send mail

**Comment by jagarwa1** [comment]
Env variables for SMTP Credentials set in apache config. PHPMailer does not require local mail server, which is why we're using it now
